### ISSUE TITLE
xclip missing parameters

### ISSUE THREAD

**Issue by jfeick** [jreinert/autopass#18]
I'm using awesomewm for my window manager, and autopass does not copy contents to clipboard using xclip.
To use the clipboard functionality I have to explicitly use`xclip -selection clipboard`

e.g.
Line 444:
```
def copy(attribute, notification_seconds = 5)
  clear_clip_pidfile = '/tmp/autopass-clear-clip.pid'
  value = @entry.attributes[attribute]

  if File.exist?(clear_clip_pidfile)
    Process.kill(:INT, File.read(clear_clip_pidfile).to_i)
  end
  IO.popen('xclip -selection clipboard', 'w+') { |io| io.print(value) }
  notify("Copied #{attribute} to clipboard. Clearing in 45 seconds", :normal, notification_seconds*1000)
  fork do
    File.write(clear_clip_pidfile, Process.pid)
    sleep(45)
    IO.popen('xclip -selection clipboard', 'w+') { |io| io.print('') }
    File.delete(clear_clip_pidfile)
  end
end
```

Couldnt this behaviour be implemented using a configuration file? (perhaps even to change xclip with another clipboard tool?)

**Comment by repomaa** [comment]
Sure. I'd be happy to add a config option for the clipboard selection. By default xclip uses the x primary clipboard (from which you paste using the middle mouse button or shift+insert). I almost never use -selection clipboard which is why i didn't think of this as an isssue. Would you want to make a pull request for this?

**Comment by jfeick** [comment]
@jreinert done.
See: [Pull request](https://github.com/jreinert/autopass/pull/20)
