### ISSUE TITLE
Error while copying another password while previous password is not yet cleared

### ISSUE THREAD

**Issue by jfeick** [jreinert/autopass#19]
I'm getting the following messages when I try to copy another password or username while the previous entry has not yet been cleared:

``` 
/usr/bin/autopass:455:in `sleep': Interrupt
	from /usr/bin/autopass:455:in `block in copy'
	from /usr/bin/autopass:453:in `fork'
	from /usr/bin/autopass:453:in `copy'
	from /usr/bin/autopass:465:in `<main>'
```

**Comment by repomaa** [comment]
yes, this is by design. When you copy a password autopass forks and exits. The forked process sleeps for a while before clearing the password from the clipboard. If you open another autopass instance and copy another password the new instance will kill the previously forked process with SIGINT. This is why you will see Interrupt in the output.
