### ISSUE TITLE
autopass fails to copy/autotype under arch

### ISSUE THREAD

**Issue by Maesto** [jreinert/autopass#4]
autopass fails to autotype/ copy username / copy password with this error:

```
[user@hostname ~]$ autopass
/usr/bin/autopass:291:in `<main>': undefined method `autotype!' for nil:NilClass (NoMethodError)
```

**Comment by repomaa** [comment]
earlier changes broke this since as of now the git version of rofi is needed. autopass makes use of the new fuzzy search feature in rofi and seems to break for earlier versions. Please use the rofi-git aur package or compile it from the git repo in other distros.

Will close after updating the PKGBUILD
